### ISSUE TITLE
Add "phpparser" task to grumphp's config

### ISSUE THREAD

**Issue by vyshkant** [inslav/polesian-archive#1]
- [ ] run `composer require --dev nikic/php-parser`
- [ ] add the following task to grumphp.yml when https://github.com/phpro/grumphp/issues/508 is resolved:

```yaml
phpparser:
  visitors:
    declare_strict_types: ~
    forbidden_function_calls:
      blacklist:
      - 'var_dump'
    no_exit_statements: ~
  metadata:
    priority: -85
```
